name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build

    - name: Deploy to Pages
      run: |
        cd dist 
        git init
        git config user.name "lxdora"
        git config user.email "${{ secrets.GIT_EMAIL }}"
        git add -A
        git commit -m 'deploy'
        git push -f https://lxdora:${{ secrets.ACCESS_TOKEN }}@github.com/lxdora/vue-drag-group master:gh-pages

        cd -